### ISSUE TITLE
"This app can't run on your PC" | Can't install StandSupportTool

### ISSUE THREAD

**Issue by yellowdude040212** [AXOca/StandSupportTool#11]
How to fix this ?

I cannot use StandSupportTool without installing "windowsdesktop-runtime"

But when I try to install it, it says my PC cannot run it.

![image](https://github.com/user-attachments/assets/cc80cb71-3655-4f4b-891c-458071d7ef93)

**Comment by alessandromrc** [comment]
Dupe of #10
