### ISSUE TITLE
Session, departure of players

### ISSUE THREAD

**Issue by YurikViskonti** [AXOca/StandSupportTool#13]
I have a problem that has been going on for a week now, and it's not just me, my friend creates a session, and people come when I enter the session, and first the whole session sends me love letters, and the whole session disappears, how long can it last, it's been 4 days, an update came out today, I thought it was fixed, but still not, it's impossible to play. Is this a problem for all players with this menu, when will you fix it?

**Comment by alessandromrc** [comment]
> I have a problem that has been going on for a week now, and it's not just me, my friend creates a session, and people come when I enter the session, and first the whole session sends me love letters, and the whole session disappears, how long can it last, it's been 4 days, an update came out today, I thought it was fixed, but still not, it's impossible to play. Is this a problem for all players with this menu, when will you fix it?

Learn how to read the README of a repository, thanks.

**Comment by YurikViskonti** [comment]
And where can I find him? How will it help if the players are kicked out of the session, other people with menus without being the leader in the session cannot play in the session.
