### ISSUE TITLE
Translating to Spanish missing info

### ISSUE THREAD

**Issue by ExoticGamerrrYT** [AXOca/StandSupportTool#5]
Hello! My main language is Spanish and when I saw the to-do list I wanted to contribute to this project, but I didn't find any information in the readme file about this; so I wonder if the creator can help me.
Thanks in advance.

**Comment by alessandromrc** [comment]
We currently don't support translations as of now since it wasn't a core feature, it might get added soon but there's still no ETA.

Thanks for your interest on our project.

**Comment by ExoticGamerrrYT** [comment]
Thanks for the reply! I'll keep an eye out for future updates. If at any time you need help with Spanish translations, I'll be happy to help. Keep up the good work!
